import { useState, type ReactNode } from 'react'
import { usePageState, useTraps } from '../../core/playground'
import type { PageMeta } from '../../core/registry'
import { useSyncedState } from './part2State'

export const meta: PageMeta = {
  path: '/ui/misc',
  title: 'Odd locators gallery',
  group: 'General UI',
  summary:
    'Every awkward locator pattern side by side: split text, mismatched accessible names, CSS-generated text, transformed text, invisible characters, icon-only and role-less buttons, hidden clones, off-screen inputs, duplicate test ids, generated ids and names, deep nesting, shuffled lists and conditional links.',
  order: 16,
  samples: [
    {
      id: 'M1',
      title: 'Text split across spans',
      steps: ['Navigate to <base>/ui/misc/', 'Click on "Submit"'],
      expected: 'state.hits.split = 1 (the label is "Sub" + "mit" in two spans).',
    },
    {
      id: 'M2',
      title: 'Hidden clone before the real button',
      steps: ['Click on "Confirm"'],
      expected: 'state.hits.realConfirm = 1 and state.hits.hiddenConfirm is absent.',
    },
    {
      id: 'M3',
      title: 'Off-screen checkbox with a visible proxy',
      steps: ['Click on "I accept the terms"'],
      expected: 'state.offscreenChecked = true.',
    },
    {
      id: 'M4',
      title: 'Generated ids and names',
      steps: ['Enter Example Ltd in the "Account name" field', 'Enter REF-42 in the "Reference code" field'],
      expected: 'state.accountName = "Example Ltd", state.referenceCode = "REF-42"; the id looks like input-1234 and the name is a UUID.',
    },
    {
      id: 'M5',
      title: 'Shuffled list',
      query: 'shuffle=true',
      steps: ['Click on "Charlie"'],
      expected: 'state.hits.list = "Charlie" whatever the order (seeded by seed=).',
    },
    {
      id: 'M6',
      title: 'Link that is sometimes plain text',
      steps: ['Click on "View details" if Present'],
      expected: 'state.linkRendered tells whether it was a link for this seed; state.hits.link = 1 only when it was.',
    },
  ],
}

function Trap({ title, trap, children, testid }: { title: string; trap: string; children: ReactNode; testid: string }) {
  return (
    <section data-ui="card" data-testid={`trap-${testid}`} aria-label={title}>
      <h2 style={{ marginTop: 0, fontSize: '1.05rem' }}>{title}</h2>
      <p data-ui="hint">Trap: {trap}</p>
      {children}
    </section>
  )
}

const LIST = ['Alpha', 'Bravo', 'Charlie', 'Delta', 'Echo']

function Deep({ depth, children }: { depth: number; children: ReactNode }) {
  if (depth <= 0) return <>{children}</>
  return (
    <div data-depth={depth} style={{ paddingLeft: 1 }}>
      <Deep depth={depth - 1}>{children}</Deep>
    </div>
  )
}

export default function MiscPage() {
  const t = useTraps('misc')
  const { state, merge } = usePageState()
  const hits = (state.hits as Record<string, number | string>) ?? {}
  const hit = (k: string) => merge({ hits: { ...hits, [k]: ((hits[k] as number) ?? 0) + 1 } })
  const count = (k: string) => <span data-ui="hint" data-testid={`count-${k}`}> clicks: {(hits[k] as number) ?? 0}</span>
  const [offChecked, setOffChecked] = useState(false)
  const linkIsLink = t.rand('detail-link') < 0.5
  const accountId = t.numericId('input')
  const refName = t.uuid('field')
  useSyncedState({ linkRendered: linkIsLink })

  const cards: { key: string; node: ReactNode }[] = [
    {
      key: 'split',
      node: (
        <Trap title="Split text" trap="the label is split across two spans, so the text node never equals the full label." testid="split">
          <button id={t.id('split-btn')} className={t.cls('btn btn--split')} onClick={() => hit('split')}>
            <span>
              <span>Sub</span>
              <span>{t.v('mit', 'mit form')}</span>
            </span>
          </button>
          {count('split')}
        </Trap>
      ),
    },
    {
      key: 'aria',
      node: (
        <Trap title="Visible text differs from accessible name" trap='the button shows "Go" but its aria-label is "Proceed to next step".' testid="aria">
          <button id={t.id('aria-btn')} className={t.cls('btn btn--aria')} aria-label="Proceed to next step" onClick={() => hit('aria')}>
            Go
          </button>
          {count('aria')}
        </Trap>
      ),
    },
    {
      key: 'before',
      node: (
        <Trap title="Text from CSS ::before" trap="the label is generated by CSS content, so it is not in the DOM text." testid="before">
          <style>{'[data-tp-before-label]::before { content: attr(data-tp-before-label); }'}</style>
          <button id={t.id('before-btn')} className={t.cls('btn btn--before')} data-tp-before-label="Continue" data-testid="css-before-btn" onClick={() => hit('before')} />
          {count('before')}
        </Trap>
      ),
    },
    {
      key: 'upper',
      node: (
        <Trap title="text-transform: uppercase" trap='shown as "DOWNLOAD REPORT" but the DOM text is "Download report".' testid="upper">
          <button id={t.id('upper-btn')} className={t.cls('btn btn--upper')} style={{ textTransform: 'uppercase' }} onClick={() => hit('upper')}>
            Download report
          </button>
          {count('upper')}
        </Trap>
      ),
    },
    {
      key: 'chars',
      node: (
        <Trap title="Invisible characters" trap="one label has a non-breaking space, the other a zero-width space inside the word." testid="chars">
          <div data-ui="inline">
            <button id={t.id('nbsp-btn')} className={t.cls('btn btn--nbsp')} onClick={() => hit('nbsp')}>
              {'Save draft'}
            </button>
            {count('nbsp')}
            <button id={t.id('zwsp-btn')} className={t.cls('btn btn--zwsp')} onClick={() => hit('zwsp')}>
              {'Pub​lish'}
            </button>
            {count('zwsp')}
          </div>
        </Trap>
      ),
    },
    {
      key: 'icon',
      node: (
        <Trap title="Icon-only button" trap="no text and no aria-label; only an SVG <title> says what it is." testid="icon">
          <button id={t.id('icon-btn')} className={t.cls('btn btn--icon')} data-testid="icon-only-btn" onClick={() => hit('icon')} style={{ padding: 6 }}>
            <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <title>Gear icon</title>
              <circle cx="12" cy="12" r="3" />
              <path d="M12 2v3M12 19v3M2 12h3M19 12h3M4.9 4.9l2.1 2.1M17 17l2.1 2.1M4.9 19.1 7 17M17 7l2.1-2.1" />
            </svg>
          </button>
          {count('icon')}
        </Trap>
      ),
    },
    {
      key: 'div',
      node: (
        <Trap title="Div without a role" trap="looks like a button but is a plain div: no role, not focusable." testid="div">
          <div id={t.id('div-btn')} className={t.cls('btn btn--div')} data-ui="btn" onClick={() => hit('div')} style={{ display: 'inline-block' }}>
            {t.v('Apply filter', 'Apply filters')}
          </div>
          {count('div')}
        </Trap>
      ),
    },
    {
      key: 'hidden',
      node: (
        <Trap title="Hidden clone first" trap="a display:none button with the same label comes before the real one." testid="hidden">
          <button id={t.id('confirm-hidden')} className={t.cls('btn btn--confirm')} style={{ display: 'none' }} onClick={() => hit('hiddenConfirm')}>
            Confirm
          </button>
          <button id={t.id('confirm-real')} className={t.cls('btn btn--confirm')} onClick={() => hit('realConfirm')}>
            Confirm
          </button>
          {count('realConfirm')}
        </Trap>
      ),
    },
    {
      key: 'offscreen',
      node: (
        <Trap title="Off-screen input" trap="the real checkbox sits at left:-9999px; only the styled proxy label is visible." testid="offscreen">
          <div style={{ position: 'relative' }}>
            <input
              type="checkbox"
              id="offscreen-terms"
              data-testid="offscreen-input"
              checked={offChecked}
              style={{ position: 'absolute', left: -9999 }}
              onChange={(e) => {
                setOffChecked(e.target.checked)
                merge({ offscreenChecked: e.target.checked })
              }}
            />
            <label htmlFor="offscreen-terms" data-ui="btn" data-tone={offChecked ? 'success' : undefined} style={{ cursor: 'pointer' }}>
              {offChecked ? '☑' : '☐'} I accept the terms
            </label>
          </div>
        </Trap>
      ),
    },
    {
      key: 'dupTestId',
      node: (
        <Trap title="Duplicate data-testid" trap='both buttons have data-testid="action-btn".' testid="duptestid">
          <div data-ui="inline">
            <button data-testid="action-btn" id={t.id('approve-btn')} className={t.cls('btn btn--action')} onClick={() => merge({ hits: { ...hits, action: 'Approve' } })}>
              Approve
            </button>
            <button data-testid="action-btn" id={t.id('reject-btn')} className={t.cls('btn btn--action')} onClick={() => merge({ hits: { ...hits, action: 'Reject' } })}>
              Reject
            </button>
          </div>
        </Trap>
      ),
    },
    {
      key: 'numeric',
      node: (
        <Trap title="CRM-style numeric ids" trap={`the input id is generated (now "${accountId}") and changes with unstableIds.`} testid="numeric">
          <label htmlFor={accountId} style={{ display: 'block' }}>
            Account name
          </label>
          <input id={accountId} onChange={(e) => merge({ accountName: e.target.value, accountInputId: accountId })} />
        </Trap>
      ),
    },
    {
      key: 'uuid',
      node: (
        <Trap title="UUID names" trap="the input has no id, only a generated UUID name attribute." testid="uuid">
          <label data-ui="field">
            <span>Reference code</span>
            <input name={refName} onChange={(e) => merge({ referenceCode: e.target.value, referenceName: refName })} />
          </label>
        </Trap>
      ),
    },
    {
      key: 'deep',
      node: (
        <Trap title="Deep nesting" trap="the target is wrapped in 15 anonymous divs, so absolute XPaths are very long." testid="deep">
          <Deep depth={15}>
            <button id={t.id('deep-btn')} className={t.cls('btn btn--deep')} onClick={() => hit('deep')}>
              Deep target
            </button>
            {count('deep')}
          </Deep>
        </Trap>
      ),
    },
    {
      key: 'list',
      node: (
        <Trap title="Shuffled list" trap="with shuffle=true the order changes per seed; index-based locators break." testid="list">
          <ul data-testid="shuffled-list" style={{ display: 'flex', gap: 8, listStyle: 'none', padding: 0, flexWrap: 'wrap' }}>
            {t.shuffle(LIST, 'items').map((x) => (
              <li key={x}>
                <button className={t.cls('btn btn--item')} onClick={() => merge({ hits: { ...hits, list: x } })}>
                  {x}
                </button>
              </li>
            ))}
          </ul>
        </Trap>
      ),
    },
    {
      key: 'link',
      node: (
        <Trap title="Sometimes a link" trap={`depending on the seed this is a link or plain text (seed ${t.config.seed}: ${linkIsLink ? 'link' : 'text'}).`} testid="link">
          {linkIsLink ? (
            <a
              href="#details"
              id={t.id('detail-link')}
              className={t.cls('link link--details')}
              onClick={(e) => {
                e.preventDefault()
                hit('link')
              }}
            >
              View details
            </a>
          ) : (
            <span id={t.id('detail-text')}>View details</span>
          )}
          {count('link')}
        </Trap>
      ),
    },
  ]

  return (
    <>
      <div data-ui="grid" style={{ gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: 12 }}>
        {t.v(cards, [...cards].reverse()).map((c) => (
          <div key={c.key}>{c.node}</div>
        ))}
      </div>
    </>
  )
}

